<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotFly.Core\DotFly.Core.csproj" />
    <ProjectReference Include="..\..\src\DotFly.Engine\DotFly.Engine.csproj" />
    <ProjectReference Include="..\..\src\DotFly.Adapters.MLNet\DotFly.Adapters.MLNet.csproj" />
    <ProjectReference Include="..\..\src\DotFly.Adapters.Onnx\DotFly.Adapters.Onnx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" />
    <PackageReference Include="Microsoft.ML.OnnxConverter" />
  </ItemGroup>

</Project>
